# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                backoffice/src/client/.*|
                backend/app/templates/.*
            )$
      - id: trailing-whitespace
        exclude: ^backoffice/src/client/.*
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: pnpm run lint
        language: system
        types: [text]
        files: ^backoffice/

      - id: local-ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: python
        types: [python]

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --exit-non-zero-on-format
        require_serial: true
        language: python
        types: [python]

      - id: generate-backoffice-sdk
        name: Generate Backoffice SDK
        entry: bash ./scripts/generate-client.sh
        pass_filenames: false
        language: system
        files: ^backend/.*$|^scripts/generate-client\.sh$
